# Generated by Django 5.0.2 on 2024-02-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glocos', models.FloatField(max_length=10)),
                ('bmi', models.FloatField(max_length=10)),
                ('prusser', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checkIn', models.DateTimeField(auto_now_add=True)),
                ('checkOut', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
